name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - '**.firebaserc'
  workflow_dispatch:



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Install dependencies
      run: npm install astro

    - name: Install dependencies
      run: npm install -g firebase-tools

    - name: Build and test
      run: npm run build

    - name: Deploy to Firebase
      run: firebase deploy --token 4/0Ab_5qll6-fw0MlD0mk7gzOP3vtseEEwlfBvWA-4H65P3jB0geyXcYljqhRtQxmru5W5J7A

